name: ultimate_finance_app
description: "Totally local finance app for you to take control of your money"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  freezed_annotation: ^3.1.0
  cloud_firestore: ^6.0.1
  equatable: ^2.0.7
  fl_chart: ^1.1.0
  go_router: ^16.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  gsheets: ^0.5.0
  firebase_remote_config: ^6.1.0
  get_it: ^7.6.7
  injectable: ^2.4.1

dev_dependencies:
  build_runner: ^2.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  integration_test:
    sdk: flutter
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
