name: widget_catalog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  ultimate_finance_app:
    path: ../
  widgetbook: 3.12.0
  widgetbook_annotation: 3.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  widgetbook_generator: 3.11.0
  build_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
